apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: constancy-{{ .Values.environment.name }}-ingress
  namespace: constancy-{{ .Values.environment.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.environment.hostPrefix }}constancy.live
      secretName: constancy-tls-{{ .Values.environment.name }}
  rules:
  - host: {{ .Values.environment.hostPrefix }}constancy.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.applicationName }}-ui-service
            port:
              number: 80
  - host: keycloak.{{ .Values.environment.hostPrefix }}constancy.live
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.applicationName }}-keycloak-service
              port:
                number: 8080
  - host: api.{{ .Values.environment.hostPrefix }}constancy.live
    http:
      paths:
      - path: /organizations/*
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.applicationName }}-organizations-service
            port:
              number: 8082
