apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-organizations-service
  namespace: constancy-{{ .Values.environment.name }}
  labels:
    app: {{ .Values.applicationName }}
    chart: {{ template "constancy.chart" . }}
    component: "{{ .Values.organizationsService.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  selector:
    app: {{ template "constancy.fullname" . }}
    component: "{{ .Values.organizationsService.name }}"
    release: {{ .Release.Name }}
