applicationName: constancy
replicaCount: 1

environment:
  name: production
  hostPrefix:

ui:
  name: ui
  image:
    repository: jonathanleedev/constancy-ui
    tag: 0.1.1
    pullPolicy: Always
  port: 80

api:
  name: api
  image:
    repository: jonathanleedev/constancy-api
    tag: 0.1.1
    pullPolicy: Always
  port: 3000
