applicationName: constancy
replicaCount: 1

environment:
  name: production
  hostPrefix:

ui:
  name: ui
  image:
    repository: jonathanleedev/constancy-ui
    tag: 0.1.1
    pullPolicy: Always
  port: 80

organizationsService:
  name: organizations-service
  image:
    repository: jonathanleedev/constancy-organizations-service
    tag: 0.0.1
    pullPolicy: Always
  port: 8082
