applicationName: constancy
replicaCount: 1

environment:
  name: staging
  hostPrefix: staging.

ui:
  name: ui
  image:
    repository: jonathanleedev/constancy-ui
    tag: stage-0.1.0
    pullPolicy: Always
  port: 80

organizationsService:
  name: organizations-service
  image:
    repository: jonathanleedev/constancy-organizations-service
    tag: 0.0.1
    pullPolicy: Always
  port: 8082
