constancy:
  front-end:
    url: http://localhost:4200
  keycloak:
    url: http://localhost:8080
  gateway:
    url: http://localhost:8081
  index-service:
    url: http://localhost:8082
  organization-service:
    url: http://localhost:8083
server:
  port: ${INDEX_SERVICE_PORT}
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/constancy-organization-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: constancy-java-client
            client-secret: ICMPT365ZyRAgTYZWp1Fidzhj5oSXr2g
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${constancy.keycloak.url}/realms/constancy
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${constancy.keycloak.url}/realms/constancy
